apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
      - name: init-storage
        image: busybox:1.35
        command: 
          - sh
          - -c
          - |
            mkdir -p /var/loki/boltdb-shipper-active &&
            mkdir -p /var/loki/boltdb-shipper-cache &&
            mkdir -p /var/loki/chunks &&
            mkdir -p /var/loki/wal &&
            mkdir -p /var/loki/compactor &&  # Add compactor directory
            chown -R 10001:10001 /var/loki
        volumeMounts:
        - name: storage
          mountPath: /var/loki
      containers:
      - name: loki
        image: grafana/loki:2.8.0
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
        args:
          - -config.file=/etc/loki/loki.yaml
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /var/loki
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: storage
        persistentVolumeClaim:
          claimName: loki-storage